export const ERROR_CODE = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  REQUEST_FAILED: 'REQUEST_FAILED',

  // OAuth 관련 에러
  OAUTH_PROFILE_INVALID: 'OAUTH_PROFILE_INVALID',
  OAUTH_PROVIDER_ERROR: 'OAUTH_PROVIDER_ERROR',

  // User 관련 에러
  USER_CONFLICT: 'USER_CONFLICT',
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  // Token 관련 에러
  TOKEN_ISSUE_FAILED: 'TOKEN_ISSUE_FAILED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
} as const;
